### ISSUE TITLE
Organization into modules

### ISSUE THREAD

**Issue by PetrKryslUCSD** [PetrKryslUCSD/JFinEALE.jl#2]
It seems to me that the organization  of JFinEALE into  two levels of modules offers the most flexibility. At the same time, leveling out of the structure  into a single namespace is not precluded.

Consider the following example:

module A

module B
function test2(n)
   println("$n in module B")
end
export test2
end   # end module B

module C
function test3(n)
   println("$n in module C")
end
export test3
end    # end module C

using .B
export test2
using A.C
export test3

end     # end module A

This allows "using A" to provide access to both  test2 and test3 as if they were defined in module A.  

julia> include("modls.jl")

julia> using A

julia> test3(3)
3 in module C

julia> test2(3)
3 in module B

At the same time  functions can be referenced  with the fully qualified module name (for instance A.b.test2). In case the  leveling out proves  troublesome (conflicts?),  The export from  module A can be  painlessly eliminated.

julia> A.test2(3)
3 in module B

**Comment by goedman** [comment]
Hi Petr,

Did a number of experiments along what you suggested and I think that will work fine.

There are a couple of special cases that need to be handled with care. You already asked the steadystate question. There was an email earlier today with one suggestion how that could be fixed.

There are also some function names that are duplicating Base names (count, subset come to mind).

Let me know if you want to create a branch with this structure or if you want me to do it.

Regards,
Rob

**Comment by goedman** [comment]
Petr,

The master branch in my repo contains the experiments I mentioned. The very last step I did was a mistake, I'll fix those a bit later this morning. 

We could opt to only export from JFinEALE what is typically needed for applications. I also wondered if it would be useful to separate heat and strength modules, although right now it certainly doesn't hurt to include them all.

Rob

**Comment by goedman** [comment]
Hi Petr,

Fixed the previous mistake, removed the old PkgStruc branch. The Master branch is now up to date, I think along your suggestion. I added a domain argument to steady state and exported an initial (dummy) version in JFinEALE.jl to overcome the issue in your question. All examples seem to run fine.

Travis appears happy as well, both the latest release and the nightly build.

Rob

**Comment by PetrKryslUCSD** [comment]
Rob,

Thanks for the update.  I would like to see what the fallout from the
current conversation on the users group  will be  concerning the structure
of the package.  Perhaps it is not such a great idea  to have exports all
over the place.   At this point  I don't know: the arguments against are
also  quite good, as I believe my arguments for exports  are.

Petr



On Tue, Jan 13, 2015 at 11:28 AM, Rob J Goedman <notifications@github.com>
wrote:

> Hi Petr,
>
> Fixed the previous mistake, removed the old PkgStruc branch. The Master
> branch is now up to date, I think along your suggestion. I added a domain
> argument to steady state and exported an initial (dummy) version in
> JFinEALE.jl to overcome the issue in your question. All examples seem to
> run fine.
>
> Travis appears happy as well, both the latest release and the nightly
> build.
>
> Rob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PetrKryslUCSD/JFinEALE.jl/issues/2#issuecomment-69803627>
> .
>



-- 
Petr Krysl
Professor
University of California, San Diego
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by PetrKryslUCSD** [comment]
The  two-level  structure of modules seems like a good one.  The top-level module (JFinEALE)   also exports the symbols from the constituent submodules,  which can be convenient.

Note that the  "export"  statements are all  on  separate lines  which makes it possible to automatically on comment that exports if needed.

I also reverted to  using the algorithm functions  by qualification with the module name.  Distinguishing between the algorithm functions by reference  to an artificial (empty)  type  in the end did not seem very satisfying.

Tests are passed, the examples have not been updated yet though.

**Comment by goedman** [comment]
Hi Petr,

The two-level structure certainly seems to work fine. Limiting exports at the top level could turn into a real benefit if it would reduce the surface area of the api for end-users (and thus end-user documentation).

Artificial empty types pop up regularly on the user mailing list, I assume often related to taking advantage of multiple dispatch. I agree it feels like overkill in this case.

I was wondering if by distinguishing domains like heat_conduction, acoustics and in my case strength, one could limit initial parsing time (although parsing time is not an issue right now for JFinEALE). The effect of jit remains striking in some examples, e.g the fahy_H8_example.jl.

In general I think the 'using' preambles in the examples are minimal now. In some cases, like steadystate() and the MeshExportModule constants (e.g.H8), full qualification is required (or additional using statements), but I think that is ok.

Regards,
Rob

**Comment by PetrKryslUCSD** [comment]
Rob,

Glad you came to the same assessment of the currect package structure.

I am now working on the initial port of stress analysis (linear
deformation)...

P

**Comment by PetrKryslUCSD** [comment]
Package structure adopted.
