### ISSUE TITLE
Slow creation of sparse matrices from IJV in Base.

### ISSUE THREAD

**Issue by KristofferC** [PetrKryslUCSD/JFinEALE.jl#4]
Maybe interesting for you too:

https://github.com/JuliaLang/julia/issues/10694

**Comment by PetrKryslUCSD** [comment]
This is an interesting observation.  Where does the in-line_sparse come
from?

On Tue, Mar 31, 2015 at 9:42 AM, Kristoffer Carlsson <
notifications@github.com> wrote:

> Maybe interesting for you too:
>
> JuliaLang/julia#10694 <https://github.com/JuliaLang/julia/issues/10694>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PetrKryslUCSD/JFinEALE.jl/issues/4>.
>



-- 
Petr Krysl
Professor
University of California, San Diego
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by KristofferC** [comment]
I just copied the function in csparse.jl and manually inlined the plus.

**Comment by KristofferC** [comment]
Well, now you know about it :) For simple problems, the creation of the sparse matrix is significant so it can give quite nice speed up.
